apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobber-gateway-ingress
  namespace: production
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: jobber-gateway-ingress
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /gateway-health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/subnets: <subnet-public-1-id>,<subnet-public-2-id> # Replace with your public subnet IDs
    alb.ingress.kubernetes.io/auth-session-cookie: session
    alb.ingress.kubernetes.io/target-group-attributes: idle_timeout.timeout_seconds=300,deregistration_delay.timeout_seconds=60
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: api.jobberapp.kevmendeveloper.com

spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: jobber-gateway
      port: 
        number: 4000
  tls:
    - hosts:
      - "*.jobberapp.kevmendeveloper.com"
  rules:
  - host: api.jobberapp.kevmendeveloper.com
    http:
      paths:
      - path: /gateway-health
        pathType: Exact
        backend:
          service:
            name: jobber-gateway
            port: 
              number: 4000
      - path: /api/gateway/v1
        pathType: Prefix
        backend:
          service:
            name: jobber-gateway
            port: 
              number: 4000