apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobber-grafana-ingress
  namespace: grafana
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: jobber-grafana-ingress
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: "3000"
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '120'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '10'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/subnets: <subnet-public-1-id>,<subnet-public-2-id> # Replace with your public subnet IDs
    alb.ingress.kubernetes.io/target-type: ip
    # Replace with the security group ID of the worker nodes remoteAccess security group
    alb.ingress.kubernetes.io/security-groups: <sg-alb-id>
    external-dns.alpha.kubernetes.io/hostname: grafana.jobberapp.kevmendeveloper.com

spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: grafana
      port: 
        number: 80
  tls:
    - hosts:
      - grafana.jobberapp.kevmendeveloper.com
      - "*.jobberapp.kevmendeveloper.com"
  rules:
  - host: grafana.jobberapp.kevmendeveloper.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port: 
              number: 80