apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobber-prometheus-ingress
  namespace: prometheus
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: jobber-prometheus-ingress
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /-/healthy
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/subnets: <subnet-public-1-id>,<subnet-public-2-id> # Replace with your public subnet IDs
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: <sg-alb-id> # Replace with your ALB security group ID
    alb.ingress.kubernetes.io/certificate-arn: <certificate-arn> # Replace with your ACM certificate ARN
    external-dns.alpha.kubernetes.io/hostname: prometheus.jobberapp.kevmendeveloper.com

spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: prometheus-server
      port:
        number: 80
  tls:
    - hosts:
      - prometheus.jobberapp.kevmendeveloper.com
      - "*.jobberapp.kevmendeveloper.com"
  rules:
  - host: prometheus.jobberapp.kevmendeveloper.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-server
            port:
              number: 80